const ActionTypes = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT: 'LOGOUT',
  FETCH_MY_ARTICLES: 'FETCH_MY_ARTICLES',
  FETCH_ALL_PUBLIC_ARTICLES: 'FETCH_ALL_PUBLIC_ARTICLES',
  ADD_NEW_ARTICLE: 'ADD_NEW_ARTICLE',
  ADD_NEW_ARTICLE_SUCCESS: 'ADD_NEW_ARTICLE_SUCCESS',
  ADD_NEW_ARTICLE_ERROR: 'ADD_NEW_ARTICLE_ERROR',
};

export default ActionTypes;
